apiVersion: v1
kind: ConfigMap
metadata:
  name: shopping-web-config
  namespace: ecommerce
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS: "http://+:80"
  ApiSettings__GatewayAddress: "http://api-gateway"
