apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shopping-web
  namespace: ecommerce
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: shop.ecommerce.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shopping-web
                port:
                  number: 80
