replicaCount: 1

image:
  repository: ghanem22/basket-api
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

config:
  aspnetCoreEnvironment: Development
  aspnetCoreUrls: http://+:80
  dbHost: basket-db
  dbPort: "5432"
  dbName: basket
  messageBrokerHost: amqp://ecommerce-mq:5672
  redisConnection: redis:6379
  discountGrpcUrl: http://discount-grpc

secret:
  dbUser: postgres
  dbPassword: postgres
  messageBrokerUser: guest
  messageBrokerPassword: guest

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi
