{{- $name := "ordering-api" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}-config
  labels:
    app: ordering-api
    release: {{ .Release.Name }}
data:
  ASPNETCORE_ENVIRONMENT: "{{ .Values.config.aspnetCoreEnvironment }}"
  ASPNETCORE_URLS: "{{ .Values.config.aspnetCoreUrls }}"
  DB_HOST: "{{ .Values.config.dbHost }}"
  DB_PORT: "{{ .Values.config.dbPort }}"
  DB_NAME: "{{ .Values.config.dbName }}"
  MESSAGE_BROKER_HOST: "{{ .Values.config.messageBrokerHost }}"
  FEATURE_ORDER_FULLFILMENT: "{{ .Values.config.featureOrderFullfilment }}"
