{{- $name := "ordering-api" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}-secret
  labels:
    app: ordering-api
    release: {{ .Release.Name }}
type: Opaque
stringData:
  DB_USER: "{{ .Values.secret.dbUser }}"
  DB_PASSWORD: "{{ .Values.secret.dbPassword }}"
  MESSAGE_BROKER_USERNAME: "{{ .Values.secret.messageBrokerUser }}"
  MESSAGE_BROKER_PASS: "{{ .Values.secret.messageBrokerPassword }}"
