apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-api-config
  namespace: ecommerce
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS: "http://+:80"
  DB_HOST: "catalog-db"
  DB_PORT: "5432"
  DB_NAME: "catalog"
