apiVersion: v1
kind: ConfigMap
metadata:
  name: basket-api-config
  namespace: ecommerce
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS: "http://+:80"
  DB_HOST: "basket-db"
  DB_PORT: "5432"
  DB_NAME: "basket"
  MESSAGE_BROKER_HOST: amqp://ecommerce-mq:5672