apiVersion: v1
kind: Secret
metadata:
  name: basket-api-secret
  namespace: ecommerce
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  MESSAGE_BROKER_USERNAME: "guest"
  MESSAGE_BROKER_PASS: "guest"