apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  labels:
    app: ecommerce-mq
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: "{{ .Values.statefulset.credentials.username }}"
  RABBITMQ_DEFAULT_PASS: "{{ .Values.statefulset.credentials.password }}"
