apiVersion: v1
kind: Service
metadata:
  name: ecommerce-mq
  labels:
    app: ecommerce-mq
spec:
  selector:
    app: ecommerce-mq
  ports:
    - name: amqp
      port: 5672
      targetPort: 5672
    - name: management
      port: 15672
      targetPort: 15672
